POST http://localhost:8888/encrypt
Content-Type: application/x-www-form-urlencoded

fae65baf-c60a-42a0-a977-ddbb54afaf1c

###

POST http://localhost:8888/actuator/refresh

###

GET http://localhost:8888/pcb-main/default
